export interface City {
  id: string;
  name: string;
  stateId: string;
}

export interface State {
  id: string;
  name: string;
  cities: City[];
}

export const nigeriaStates: State[] = [
  {
    id: "abia",
    name: "Abia",
    cities: [
      { id: "aba", name: "Aba", stateId: "abia" },
      { id: "arochukwu", name: "Arochukwu", stateId: "abia" },
      { id: "bende", name: "Bende", stateId: "abia" },
      { id: "ikwuano", name: "Ikwuano", stateId: "abia" },
      { id: "isiala-ngwa", name: "Isiala Ngwa", stateId: "abia" },
      { id: "isuikwuato", name: "Isuikwuato", stateId: "abia" },
      { id: "obi-ngwa", name: "Obi Ngwa", stateId: "abia" },
      { id: "ohafia", name: "Ohafia", stateId: "abia" },
      { id: "osisioma", name: "Osisioma", stateId: "abia" },
      { id: "ugwunagbo", name: "Ugwunagbo", stateId: "abia" },
      { id: "ukwa-east", name: "Ukwa East", stateId: "abia" },
      { id: "ukwa-west", name: "Ukwa West", stateId: "abia" },
      { id: "umuahia", name: "Umuahia", stateId: "abia" },
      { id: "umu-nneochi", name: "Umu Nneochi", stateId: "abia" }
    ]
  },
  {
    id: "adamawa",
    name: "Adamawa",
    cities: [
      { id: "demsa", name: "Demsa", stateId: "adamawa" },
      { id: "fufore", name: "Fufore", stateId: "adamawa" },
      { id: "ganye", name: "Ganye", stateId: "adamawa" },
      { id: "gayuk", name: "Gayuk", stateId: "adamawa" },
      { id: "gombi", name: "Gombi", stateId: "adamawa" },
      { id: "grie", name: "Grie", stateId: "adamawa" },
      { id: "hong", name: "Hong", stateId: "adamawa" },
      { id: "jada", name: "Jada", stateId: "adamawa" },
      { id: "lamurde", name: "Lamurde", stateId: "adamawa" },
      { id: "madagali", name: "Madagali", stateId: "adamawa" },
      { id: "maiha", name: "Maiha", stateId: "adamawa" },
      { id: "mayo-belwa", name: "Mayo Belwa", stateId: "adamawa" },
      { id: "michika", name: "Michika", stateId: "adamawa" },
      { id: "mubi-north", name: "Mubi North", stateId: "adamawa" },
      { id: "mubi-south", name: "Mubi South", stateId: "adamawa" },
      { id: "numan", name: "Numan", stateId: "adamawa" },
      { id: "shelleng", name: "Shelleng", stateId: "adamawa" },
      { id: "song", name: "Song", stateId: "adamawa" },
      { id: "toungo", name: "Toungo", stateId: "adamawa" },
      { id: "yola-north", name: "Yola North", stateId: "adamawa" },
      { id: "yola-south", name: "Yola South", stateId: "adamawa" }
    ]
  },
  {
    id: "akwa-ibom",
    name: "Akwa Ibom",
    cities: [
      { id: "abak", name: "Abak", stateId: "akwa-ibom" },
      { id: "eastern-obolo", name: "Eastern Obolo", stateId: "akwa-ibom" },
      { id: "eket", name: "Eket", stateId: "akwa-ibom" },
      { id: "esit-eket", name: "Esit Eket", stateId: "akwa-ibom" },
      { id: "essien-udim", name: "Essien Udim", stateId: "akwa-ibom" },
      { id: "etim-ekpo", name: "Etim Ekpo", stateId: "akwa-ibom" },
      { id: "etinan", name: "Etinan", stateId: "akwa-ibom" },
      { id: "ibeno", name: "Ibeno", stateId: "akwa-ibom" },
      { id: "ibesikpo-asutan", name: "Ibesikpo Asutan", stateId: "akwa-ibom" },
      { id: "ibiono-ibom", name: "Ibiono Ibom", stateId: "akwa-ibom" },
      { id: "ika", name: "Ika", stateId: "akwa-ibom" },
      { id: "ikono", name: "Ikono", stateId: "akwa-ibom" },
      { id: "ikot-abasi", name: "Ikot Abasi", stateId: "akwa-ibom" },
      { id: "ikot-ekpene", name: "Ikot Ekpene", stateId: "akwa-ibom" },
      { id: "ini", name: "Ini", stateId: "akwa-ibom" },
      { id: "itu", name: "Itu", stateId: "akwa-ibom" },
      { id: "mbo", name: "Mbo", stateId: "akwa-ibom" },
      { id: "mkpat-enin", name: "Mkpat Enin", stateId: "akwa-ibom" },
      { id: "nsit-atai", name: "Nsit Atai", stateId: "akwa-ibom" },
      { id: "nsit-ibom", name: "Nsit Ibom", stateId: "akwa-ibom" },
      { id: "nsit-ubium", name: "Nsit Ubium", stateId: "akwa-ibom" },
      { id: "obot-akara", name: "Obot Akara", stateId: "akwa-ibom" },
      { id: "okobo", name: "Okobo", stateId: "akwa-ibom" },
      { id: "onna", name: "Onna", stateId: "akwa-ibom" },
      { id: "oron", name: "Oron", stateId: "akwa-ibom" },
      { id: "oruk-anam", name: "Oruk Anam", stateId: "akwa-ibom" },
      { id: "udung-uko", name: "Udung Uko", stateId: "akwa-ibom" },
      { id: "ukanafun", name: "Ukanafun", stateId: "akwa-ibom" },
      { id: "uruan", name: "Uruan", stateId: "akwa-ibom" },
      { id: "urue-offong-oruko", name: "Urue Offong Oruko", stateId: "akwa-ibom" },
      { id: "uyo", name: "Uyo", stateId: "akwa-ibom" }
    ]
  },
  {
    id: "anambra",
    name: "Anambra",
    cities: [
      { id: "aguata", name: "Aguata", stateId: "anambra" },
      { id: "anambra-east", name: "Anambra East", stateId: "anambra" },
      { id: "anambra-west", name: "Anambra West", stateId: "anambra" },
      { id: "anaocha", name: "Anaocha", stateId: "anambra" },
      { id: "awka-north", name: "Awka North", stateId: "anambra" },
      { id: "awka-south", name: "Awka South", stateId: "anambra" },
      { id: "ayamelum", name: "Ayamelum", stateId: "anambra" },
      { id: "dunukofia", name: "Dunukofia", stateId: "anambra" },
      { id: "ekwusigo", name: "Ekwusigo", stateId: "anambra" },
      { id: "idemili-north", name: "Idemili North", stateId: "anambra" },
      { id: "idemili-south", name: "Idemili South", stateId: "anambra" },
      { id: "ihiala", name: "Ihiala", stateId: "anambra" },
      { id: "njikoka", name: "Njikoka", stateId: "anambra" },
      { id: "nnewi-north", name: "Nnewi North", stateId: "anambra" },
      { id: "nnewi-south", name: "Nnewi South", stateId: "anambra" },
      { id: "ogbaru", name: "Ogbaru", stateId: "anambra" },
      { id: "onitsha-north", name: "Onitsha North", stateId: "anambra" },
      { id: "onitsha-south", name: "Onitsha South", stateId: "anambra" },
      { id: "orumba-north", name: "Orumba North", stateId: "anambra" },
      { id: "orumba-south", name: "Orumba South", stateId: "anambra" },
      { id: "oyi", name: "Oyi", stateId: "anambra" }
    ]
  },
  {
    id: "bauchi",
    name: "Bauchi",
    cities: [
      { id: "alkaleri", name: "Alkaleri", stateId: "bauchi" },
      { id: "bauchi", name: "Bauchi", stateId: "bauchi" },
      { id: "bogoro", name: "Bogoro", stateId: "bauchi" },
      { id: "damban", name: "Damban", stateId: "bauchi" },
      { id: "darazo", name: "Darazo", stateId: "bauchi" },
      { id: "dass", name: "Dass", stateId: "bauchi" },
      { id: "gamawa", name: "Gamawa", stateId: "bauchi" },
      { id: "ganjuwa", name: "Ganjuwa", stateId: "bauchi" },
      { id: "giade", name: "Giade", stateId: "bauchi" },
      { id: "itas-gadau", name: "Itas/Gadau", stateId: "bauchi" },
      { id: "jama-are", name: "Jama'are", stateId: "bauchi" },
      { id: "katagum", name: "Katagum", stateId: "bauchi" },
      { id: "kirfi", name: "Kirfi", stateId: "bauchi" },
      { id: "misau", name: "Misau", stateId: "bauchi" },
      { id: "ningi", name: "Ningi", stateId: "bauchi" },
      { id: "shira", name: "Shira", stateId: "bauchi" },
      { id: "tafawa-balewa", name: "Tafawa Balewa", stateId: "bauchi" },
      { id: "toro", name: "Toro", stateId: "bauchi" },
      { id: "warji", name: "Warji", stateId: "bauchi" },
      { id: "zaki", name: "Zaki", stateId: "bauchi" }
    ]
  },
  {
    id: "bayelsa",
    name: "Bayelsa",
    cities: [
      { id: "brass", name: "Brass", stateId: "bayelsa" },
      { id: "ekeremor", name: "Ekeremor", stateId: "bayelsa" },
      { id: "kolokuma-opokuma", name: "Kolokuma/Opokuma", stateId: "bayelsa" },
      { id: "nembe", name: "Nembe", stateId: "bayelsa" },
      { id: "ogbia", name: "Ogbia", stateId: "bayelsa" },
      { id: "sagbama", name: "Sagbama", stateId: "bayelsa" },
      { id: "southern-ijaw", name: "Southern Ijaw", stateId: "bayelsa" },
      { id: "yenagoa", name: "Yenagoa", stateId: "bayelsa" }
    ]
  },
  {
    id: "benue",
    name: "Benue",
    cities: [
      { id: "ado", name: "Ado", stateId: "benue" },
      { id: "agatu", name: "Agatu", stateId: "benue" },
      { id: "apa", name: "Apa", stateId: "benue" },
      { id: "buruku", name: "Buruku", stateId: "benue" },
      { id: "gboko", name: "Gboko", stateId: "benue" },
      { id: "guma", name: "Guma", stateId: "benue" },
      { id: "gwer-east", name: "Gwer East", stateId: "benue" },
      { id: "gwer-west", name: "Gwer West", stateId: "benue" },
      { id: "katsina-ala", name: "Katsina-Ala", stateId: "benue" },
      { id: "konshisha", name: "Konshisha", stateId: "benue" },
      { id: "kwande", name: "Kwande", stateId: "benue" },
      { id: "logo", name: "Logo", stateId: "benue" },
      { id: "makurdi", name: "Makurdi", stateId: "benue" },
      { id: "obi", name: "Obi", stateId: "benue" },
      { id: "ogbadibo", name: "Ogbadibo", stateId: "benue" },
      { id: "ohimini", name: "Ohimini", stateId: "benue" },
      { id: "oju", name: "Oju", stateId: "benue" },
      { id: "okpokwu", name: "Okpokwu", stateId: "benue" },
      { id: "otukpo", name: "Otukpo", stateId: "benue" },
      { id: "tarka", name: "Tarka", stateId: "benue" },
      { id: "ukum", name: "Ukum", stateId: "benue" },
      { id: "ushongo", name: "Ushongo", stateId: "benue" },
      { id: "vandeikya", name: "Vandeikya", stateId: "benue" }
    ]
  },
  {
    id: "borno",
    name: "Borno",
    cities: [
      { id: "abadam", name: "Abadam", stateId: "borno" },
      { id: "askira-uba", name: "Askira/Uba", stateId: "borno" },
      { id: "bama", name: "Bama", stateId: "borno" },
      { id: "bayo", name: "Bayo", stateId: "borno" },
      { id: "biu", name: "Biu", stateId: "borno" },
      { id: "chibok", name: "Chibok", stateId: "borno" },
      { id: "damboa", name: "Damboa", stateId: "borno" },
      { id: "dikwa", name: "Dikwa", stateId: "borno" },
      { id: "gubio", name: "Gubio", stateId: "borno" },
      { id: "guzamala", name: "Guzamala", stateId: "borno" },
      { id: "gwoza", name: "Gwoza", stateId: "borno" },
      { id: "hawul", name: "Hawul", stateId: "borno" },
      { id: "jere", name: "Jere", stateId: "borno" },
      { id: "kaga", name: "Kaga", stateId: "borno" },
      { id: "kala-balge", name: "Kala/Balge", stateId: "borno" },
      { id: "konduga", name: "Konduga", stateId: "borno" },
      { id: "kukawa", name: "Kukawa", stateId: "borno" },
      { id: "kwaya-kusar", name: "Kwaya Kusar", stateId: "borno" },
      { id: "mafa", name: "Mafa", stateId: "borno" },
      { id: "magumeri", name: "Magumeri", stateId: "borno" },
      { id: "maiduguri", name: "Maiduguri", stateId: "borno" },
      { id: "marte", name: "Marte", stateId: "borno" },
      { id: "mobbar", name: "Mobbar", stateId: "borno" },
      { id: "monguno", name: "Monguno", stateId: "borno" },
      { id: "ngala", name: "Ngala", stateId: "borno" },
      { id: "nganzai", name: "Nganzai", stateId: "borno" },
      { id: "shani", name: "Shani", stateId: "borno" }
    ]
  },
  {
    id: "cross-river",
    name: "Cross River",
    cities: [
      { id: "abi", name: "Abi", stateId: "cross-river" },
      { id: "akamkpa", name: "Akamkpa", stateId: "cross-river" },
      { id: "akpabuyo", name: "Akpabuyo", stateId: "cross-river" },
      { id: "bakassi", name: "Bakassi", stateId: "cross-river" },
      { id: "bekwarra", name: "Bekwarra", stateId: "cross-river" },
      { id: "biase", name: "Biase", stateId: "cross-river" },
      { id: "boki", name: "Boki", stateId: "cross-river" },
      { id: "calabar-municipal", name: "Calabar Municipal", stateId: "cross-river" },
      { id: "calabar-south", name: "Calabar South", stateId: "cross-river" },
      { id: "etung", name: "Etung", stateId: "cross-river" },
      { id: "ikom", name: "Ikom", stateId: "cross-river" },
      { id: "obanliku", name: "Obanliku", stateId: "cross-river" },
      { id: "obubra", name: "Obubra", stateId: "cross-river" },
      { id: "obudu", name: "Obudu", stateId: "cross-river" },
      { id: "odukpani", name: "Odukpani", stateId: "cross-river" },
      { id: "ogoja", name: "Ogoja", stateId: "cross-river" },
      { id: "yakuur", name: "Yakuur", stateId: "cross-river" },
      { id: "yala", name: "Yala", stateId: "cross-river" }
    ]
  },
  {
    id: "delta",
    name: "Delta",
    cities: [
      { id: "aniocha-north", name: "Aniocha North", stateId: "delta" },
      { id: "aniocha-south", name: "Aniocha South", stateId: "delta" },
      { id: "bomadi", name: "Bomadi", stateId: "delta" },
      { id: "burutu", name: "Burutu", stateId: "delta" },
      { id: "ethiope-east", name: "Ethiope East", stateId: "delta" },
      { id: "ethiope-west", name: "Ethiope West", stateId: "delta" },
      { id: "ika-north-east", name: "Ika North East", stateId: "delta" },
      { id: "ika-south", name: "Ika South", stateId: "delta" },
      { id: "isoko-north", name: "Isoko North", stateId: "delta" },
      { id: "isoko-south", name: "Isoko South", stateId: "delta" },
      { id: "ndokwa-east", name: "Ndokwa East", stateId: "delta" },
      { id: "ndokwa-west", name: "Ndokwa West", stateId: "delta" },
      { id: "okpe", name: "Okpe", stateId: "delta" },
      { id: "oshimili-north", name: "Oshimili North", stateId: "delta" },
      { id: "oshimili-south", name: "Oshimili South", stateId: "delta" },
      { id: "patani", name: "Patani", stateId: "delta" },
      { id: "sapele", name: "Sapele", stateId: "delta" },
      { id: "udu", name: "Udu", stateId: "delta" },
      { id: "ughelli-north", name: "Ughelli North", stateId: "delta" },
      { id: "ughelli-south", name: "Ughelli South", stateId: "delta" },
      { id: "ukwuani", name: "Ukwuani", stateId: "delta" },
      { id: "uvwie", name: "Uvwie", stateId: "delta" },
      { id: "warri-north", name: "Warri North", stateId: "delta" },
      { id: "warri-south", name: "Warri South", stateId: "delta" },
      { id: "warri-south-west", name: "Warri South West", stateId: "delta" }
    ]
  },
  {
    id: "ebonyi",
    name: "Ebonyi",
    cities: [
      { id: "abakaliki", name: "Abakaliki", stateId: "ebonyi" },
      { id: "afikpo-north", name: "Afikpo North", stateId: "ebonyi" },
      { id: "afikpo-south", name: "Afikpo South", stateId: "ebonyi" },
      { id: "ebonyi", name: "Ebonyi", stateId: "ebonyi" },
      { id: "ezza-north", name: "Ezza North", stateId: "ebonyi" },
      { id: "ezza-south", name: "Ezza South", stateId: "ebonyi" },
      { id: "ikwo", name: "Ikwo", stateId: "ebonyi" },
      { id: "ishielu", name: "Ishielu", stateId: "ebonyi" },
      { id: "ivo", name: "Ivo", stateId: "ebonyi" },
      { id: "izzi", name: "Izzi", stateId: "ebonyi" },
      { id: "ohaozara", name: "Ohaozara", stateId: "ebonyi" },
      { id: "ohaukwu", name: "Ohaukwu", stateId: "ebonyi" },
      { id: "onicha", name: "Onicha", stateId: "ebonyi" }
    ]
  },
  {
    id: "edo",
    name: "Edo",
    cities: [
      { id: "akoko-edo", name: "Akoko-Edo", stateId: "edo" },
      { id: "egor", name: "Egor", stateId: "edo" },
      { id: "esan-central", name: "Esan Central", stateId: "edo" },
      { id: "esan-north-east", name: "Esan North-East", stateId: "edo" },
      { id: "esan-south-east", name: "Esan South-East", stateId: "edo" },
      { id: "esan-west", name: "Esan West", stateId: "edo" },
      { id: "etsako-central", name: "Etsako Central", stateId: "edo" },
      { id: "etsako-east", name: "Etsako East", stateId: "edo" },
      { id: "etsako-west", name: "Etsako West", stateId: "edo" },
      { id: "igueben", name: "Igueben", stateId: "edo" },
      { id: "ikpoba-okha", name: "Ikpoba Okha", stateId: "edo" },
      { id: "oredo", name: "Oredo", stateId: "edo" },
      { id: "orhionmwon", name: "Orhionmwon", stateId: "edo" },
      { id: "ovia-north-east", name: "Ovia North-East", stateId: "edo" },
      { id: "ovia-south-west", name: "Ovia South-West", stateId: "edo" },
      { id: "owan-east", name: "Owan East", stateId: "edo" },
      { id: "owan-west", name: "Owan West", stateId: "edo" },
      { id: "uhunmwonde", name: "Uhunmwonde", stateId: "edo" }
    ]
  },
  {
    id: "ekiti",
    name: "Ekiti",
    cities: [
      { id: "ado-ekiti", name: "Ado Ekiti", stateId: "ekiti" },
      { id: "efon", name: "Efon", stateId: "ekiti" },
      { id: "ekiti-east", name: "Ekiti East", stateId: "ekiti" },
      { id: "ekiti-south-west", name: "Ekiti South-West", stateId: "ekiti" },
      { id: "ekiti-west", name: "Ekiti West", stateId: "ekiti" },
      { id: "emure", name: "Emure", stateId: "ekiti" },
      { id: "gbonyin", name: "Gbonyin", stateId: "ekiti" },
      { id: "ido-osi", name: "Ido Osi", stateId: "ekiti" },
      { id: "ijero", name: "Ijero", stateId: "ekiti" },
      { id: "ikere", name: "Ikere", stateId: "ekiti" },
      { id: "ikole", name: "Ikole", stateId: "ekiti" },
      { id: "ilejemeje", name: "Ilejemeje", stateId: "ekiti" },
      { id: "irepodun-ifelodun", name: "Irepodun/Ifelodun", stateId: "ekiti" },
      { id: "ise-orun", name: "Ise/Orun", stateId: "ekiti" },
      { id: "moba", name: "Moba", stateId: "ekiti" },
      { id: "oye", name: "Oye", stateId: "ekiti" }
    ]
  },
  {
    id: "enugu",
    name: "Enugu",
    cities: [
      { id: "aninri", name: "Aninri", stateId: "enugu" },
      { id: "awgu", name: "Awgu", stateId: "enugu" },
      { id: "enugu-east", name: "Enugu East", stateId: "enugu" },
      { id: "enugu-north", name: "Enugu North", stateId: "enugu" },
      { id: "enugu-south", name: "Enugu South", stateId: "enugu" },
      { id: "ezeagu", name: "Ezeagu", stateId: "enugu" },
      { id: "igbo-etiti", name: "Igbo Etiti", stateId: "enugu" },
      { id: "igbo-eze-north", name: "Igbo Eze North", stateId: "enugu" },
      { id: "igbo-eze-south", name: "Igbo Eze South", stateId: "enugu" },
      { id: "isi-uzo", name: "Isi Uzo", stateId: "enugu" },
      { id: "nkanu-east", name: "Nkanu East", stateId: "enugu" },
      { id: "nkanu-west", name: "Nkanu West", stateId: "enugu" },
      { id: "nsukka", name: "Nsukka", stateId: "enugu" },
      { id: "oji-river", name: "Oji River", stateId: "enugu" },
      { id: "udenue", name: "Udenu", stateId: "enugu" },
      { id: "udi", name: "Udi", stateId: "enugu" },
      { id: "uzouwani", name: "Uzouwani", stateId: "enugu" }
    ]
  },
  {
    id: "gombe",
    name: "Gombe",
    cities: [
      { id: "akko", name: "Akko", stateId: "gombe" },
      { id: "balanga", name: "Balanga", stateId: "gombe" },
      { id: "billiri", name: "Billiri", stateId: "gombe" },
      { id: "dukku", name: "Dukku", stateId: "gombe" },
      { id: "funakaye", name: "Funakaye", stateId: "gombe" },
      { id: "gombe", name: "Gombe", stateId: "gombe" },
      { id: "kaltungo", name: "Kaltungo", stateId: "gombe" },
      { id: "kwami", name: "Kwami", stateId: "gombe" },
      { id: "nafada", name: "Nafada", stateId: "gombe" },
      { id: "shongom", name: "Shongom", stateId: "gombe" },
      { id: "yamaltu-deba", name: "Yamaltu/Deba", stateId: "gombe" }
    ]
  },
  {
    id: "imo",
    name: "Imo",
    cities: [
      { id: "abo-mbaise", name: "Abo Mbaise", stateId: "imo" },
      { id: "ahiazu-mbaise", name: "Ahiazu Mbaise", stateId: "imo" },
      { id: "ehime-mbano", name: "Ehime Mbano", stateId: "imo" },
      { id: "ezinihitte", name: "Ezinihitte", stateId: "imo" },
      { id: "ideato-north", name: "Ideato North", stateId: "imo" },
      { id: "ideato-south", name: "Ideato South", stateId: "imo" },
      { id: "ihitte-uboma", name: "Ihitte/Uboma", stateId: "imo" },
      { id: "ikeda-north", name: "Ikeda North", stateId: "imo" },
      { id: "isu", name: "Isu", stateId: "imo" },
      { id: "mbaise", name: "Mbaise", stateId: "imo" },
      { id: "ngor-okpala", name: "Ngor Okpala", stateId: "imo" },
      { id: "njaba", name: "Njaba", stateId: "imo" },
      { id: "nkwerre", name: "Nkwerre", stateId: "imo" },
      { id: "nwangele", name: "Nwangele", stateId: "imo" },
      { id: "obowo", name: "Obowo", stateId: "imo" },
      { id: "oguta", name: "Oguta", stateId: "imo" },
      { id: "ohaji-egbema", name: "Ohaji/Egbema", stateId: "imo" },
      { id: "okigwe", name: "Okigwe", stateId: "imo" },
      { id: "onui", name: "Onui", stateId: "imo" },
      { id: "orlu", name: "Orlu", stateId: "imo" },
      { id: "oru-east", name: "Oru East", stateId: "imo" },
      { id: "oru-west", name: "Oru West", stateId: "imo" },
      { id: "owerri-municipal", name: "Owerri Municipal", stateId: "imo" },
      { id: "owerri-north", name: "Owerri North", stateId: "imo" },
      { id: "owerri-west", name: "Owerri West", stateId: "imo" },
      { id: "unuimo", name: "Unuimo", stateId: "imo" }
    ]
  },
  {
    id: "jigawa",
    name: "Jigawa",
    cities: [
      { id: "ahal", name: "Ahal", stateId: "jigawa" },
      { id: "auyo", name: "Auyo", stateId: "jigawa" },
      { id: "babura", name: "Babura", stateId: "jigawa" },
      { id: "buji", name: "Buji", stateId: "jigawa" },
      { id: "biriniwa", name: "Biriniwa", stateId: "jigawa" },
      { id: "birnin-kudu", name: "Birnin Kudu", stateId: "jigawa" },
      { id: "gumel", name: "Gumel", stateId: "jigawa" },
      { id: "guri", name: "Guri", stateId: "jigawa" },
      { id: "gwaram", name: "Gwaram", stateId: "jigawa" },
      { id: "gwiwa", name: "Gwiwa", stateId: "jigawa" },
      { id: "hadejia", name: "Hadejia", stateId: "jigawa" },
      { id: "jahun", name: "Jahun", stateId: "jigawa" },
      { id: "kafin-hausau", name: "Kafin Hausau", stateId: "jigawa" },
      { id: "kaugama", name: "Kaugama", stateId: "jigawa" },
      { id: "kazaure", name: "Kazaure", stateId: "jigawa" },
      { id: "kiri-kasama", name: "Kiri Kasama", stateId: "jigawa" },
      { id: "kiyawa", name: "Kiyawa", stateId: "jigawa" },
      { id: "maigatari", name: "Maigatari", stateId: "jigawa" },
      { id: "malam-madori", name: "Malam Madori", stateId: "jigawa" },
      { id: "miga", name: "Miga", stateId: "jigawa" },
      { id: "ringim", name: "Ringim", stateId: "jigawa" },
      { id: "roni", name: "Roni", stateId: "jigawa" },
      { id: "sule-tankarkar", name: "Sule Tankarkar", stateId: "jigawa" },
      { id: "taura", name: "Taura", stateId: "jigawa" },
      { id: "yusufari", name: "Yusufari", stateId: "jigawa" }
    ]
  },
  {
    id: "kaduna",
    name: "Kaduna",
    cities: [
      { id: "birnin-gwari", name: "Birnin Gwari", stateId: "kaduna" },
      { id: "chikun", name: "Chikun", stateId: "kaduna" },
      { id: "giwa", name: "Giwa", stateId: "kaduna" },
      { id: "igabi", name: "Igabi", stateId: "kaduna" },
      { id: "ikara", name: "Ikara", stateId: "kaduna" },
      { id: "jaba", name: "Jaba", stateId: "kaduna" },
      { id: "kachia", name: "Kachia", stateId: "kaduna" },
      { id: "kaduna-north", name: "Kaduna North", stateId: "kaduna" },
      { id: "kaduna-south", name: "Kaduna South", stateId: "kaduna" },
      { id: "kagarko", name: "Kagarko", stateId: "kaduna" },
      { id: "kajuru", name: "Kajuru", stateId: "kaduna" },
      { id: "kaura", name: "Kaura", stateId: "kaduna" },
      { id: "kauru", name: "Kauru", stateId: "kaduna" },
      { id: "kubau", name: "Kubau", stateId: "kaduna" },
      { id: "kudan", name: "Kudan", stateId: "kaduna" },
      { id: "lere", name: "Lere", stateId: "kaduna" },
      { id: "makarfi", name: "Makarfi", stateId: "kaduna" },
      { id: "sabon-gari", name: "Sabon Gari", stateId: "kaduna" },
      { id: "sanga", name: "Sanga", stateId: "kaduna" },
      { id: "soba", name: "Soba", stateId: "kaduna" },
      { id: "zangon-kataf", name: "Zangon Kataf", stateId: "kaduna" },
      { id: "zaria", name: "Zaria", stateId: "kaduna" }
    ]
  },
  {
    id: "kano",
    name: "Kano",
    cities: [
      { id: "ajeokuta", name: "Ajeokuta", stateId: "kano" },
      { id: "albasu", name: "Albasu", stateId: "kano" },
      { id: "bagwai", name: "Bagwai", stateId: "kano" },
      { id: "bebeji", name: "Bebeji", stateId: "kano" },
      { id: "bichi", name: "Bichi", stateId: "kano" },
      { id: "bunkure", name: "Bunkure", stateId: "kano" },
      { id: "dambatta", name: "Dambatta", stateId: "kano" },
      { id: "dawakin-kudu", name: "Dawakin Kudu", stateId: "kano" },
      { id: "dawakin-tofa", name: "Dawakin Tofa", stateId: "kano" },
      { id: "doguwa", name: "Doguwa", stateId: "kano" },
      { id: "fagge", name: "Fagge", stateId: "kano" },
      { id: "gabasawa", name: "Gabasawa", stateId: "kano" },
      { id: "garko", name: "Garko", stateId: "kano" },
      { id: "garun-malam", name: "Garun Malam", stateId: "kano" },
      { id: "gaya", name: "Gaya", stateId: "kano" },
      { id: "gezawa", name: "Gezawa", stateId: "kano" },
      { id: "gwale", name: "Gwale", stateId: "kano" },
      { id: "gwarzo", name: "Gwarzo", stateId: "kano" },
      { id: "kab", name: "Kab", stateId: "kano" },
      { id: "kano-municipal", name: "Kano Municipal", stateId: "kano" },
      { id: "karaye", name: "Karaye", stateId: "kano" },
      { id: "kibiya", name: "Kibiya", stateId: "kano" },
      { id: "kiru", name: "Kiru", stateId: "kano" },
      { id: "kumbotso", name: "Kumbotso", stateId: "kano" },
      { id: "kunchi", name: "Kunchi", stateId: "kano" },
      { id: "kura", name: "Kura", stateId: "kano" },
      { id: "madobi", name: "Madobi", stateId: "kano" },
      { id: "makoda", name: "Makoda", stateId: "kano" },
      { id: "minjibir", name: "Minjibir", stateId: "kano" },
      { id: "nasarawa", name: "Nasarawa", stateId: "kano" },
      { id: "rimin-gado", name: "Rimin Gado", stateId: "kano" },
      { id: "rogo", name: "Rogo", stateId: "kano" },
      { id: "sh", name: "Sh", stateId: "kano" },
      { id: "shanono", name: "Shanono", stateId: "kano" },
      { id: "sumaila", name: "Sumaila", stateId: "kano" },
      { id: "takai", name: "Takai", stateId: "kano" },
      { id: "tarauni", name: "Tarauni", stateId: "kano" },
      { id: "tofa", name: "Tofa", stateId: "kano" },
      { id: "tsanyawa", name: "Tsanyawa", stateId: "kano" },
      { id: "tudun-wada", name: "Tudun Wada", stateId: "kano" },
      { id: "ungogo", name: "Ungogo", stateId: "kano" },
      { id: "warawa", name: "Warawa", stateId: "kano" },
      { id: "wudil", name: "Wudil", stateId: "kano" }
    ]
  },
  {
    id: "katsina",
    name: "Katsina",
    cities: [
      { id: "bakori", name: "Bakori", stateId: "katsina" },
      { id: "batagarawa", name: "Batagarawa", stateId: "katsina" },
      { id: "batsari", name: "Batsari", stateId: "katsina" },
      { id: "baure", name: "Baure", stateId: "katsina" },
      { id: "bindawa", name: "Bindawa", stateId: "katsina" },
      { id: "charanchi", name: "Charanchi", stateId: "katsina" },
      { id: "dandume", name: "Dandume", stateId: "katsina" },
      { id: "danja", name: "Danja", stateId: "katsina" },
      { id: "dan-musa", name: "Dan Musa", stateId: "katsina" },
      { id: "daura", name: "Daura", stateId: "katsina" },
      { id: "dutsi", name: "Dutsi", stateId: "katsina" },
      { id: "dutsin-ma", name: "Dutsin Ma", stateId: "katsina" },
      { id: "faskari", name: "Faskari", stateId: "katsina" },
      { id: "funtua", name: "Funtua", stateId: "katsina" },
      { id: "ingawa", name: "Ingawa", stateId: "katsina" },
      { id: "jibia", name: "Jibia", stateId: "katsina" },
      { id: "kafur", name: "Kafur", stateId: "katsina" },
      { id: "kaita", name: "Kaita", stateId: "katsina" },
      { id: "kankara", name: "Kankara", stateId: "katsina" },
      { id: "kankia", name: "Kankia", stateId: "katsina" },
      { id: "katsina", name: "Katsina", stateId: "katsina" },
      { id: "kurfi", name: "Kurfi", stateId: "katsina" },
      { id: "kusada", name: "Kusada", stateId: "katsina" },
      { id: "mai-adua", name: "Mai'Adua", stateId: "katsina" },
      { id: "malumfashi", name: "Malumfashi", stateId: "katsina" },
      { id: "mani", name: "Mani", stateId: "katsina" },
      { id: "mashi", name: "Mashi", stateId: "katsina" },
      { id: "matazu", name: "Matazu", stateId: "katsina" },
      { id: "musawa", name: "Musawa", stateId: "katsina" },
      { id: "roni", name: "Roni", stateId: "katsina" },
      { id: "sab", name: "Sab", stateId: "katsina" },
      { id: "safana", name: "Safana", stateId: "katsina" },
      { id: "sandamu", name: "Sandamu", stateId: "katsina" },
      { id: "zango", name: "Zango", stateId: "katsina" }
    ]
  },
  {
    id: "kebbi",
    name: "Kebbi",
    cities: [
      { id: "aliero", name: "Aliero", stateId: "kebbi" },
      { id: "arewa-dandi", name: "Arewa Dandi", stateId: "kebbi" },
      { id: "argungu", name: "Argungu", stateId: "kebbi" },
      { id: "augie", name: "Augie", stateId: "kebbi" },
      { id: "bagudo", name: "Bagudo", stateId: "kebbi" },
      { id: "birnin-kebbi", name: "Birnin Kebbi", stateId: "kebbi" },
      { id: "bunza", name: "Bunza", stateId: "kebbi" },
      { id: "dandi", name: "Dandi", stateId: "kebbi" },
      { id: "fakai", name: "Fakai", stateId: "kebbi" },
      { id: "gara", name: "Gara", stateId: "kebbi" },
      { id: "gummi", name: "Gummi", stateId: "kebbi" },
      { id: "kalgo", name: "Kalgo", stateId: "kebbi" },
      { id: "koko-besse", name: "Koko/Besse", stateId: "kebbi" },
      { id: "maiyama", name: "Maiyama", stateId: "kebbi" },
      { id: "ngaski", name: "Ngaski", stateId: "kebbi" },
      { id: "sakaba", name: "Sakaba", stateId: "kebbi" },
      { id: "shanga", name: "Shanga", stateId: "kebbi" },
      { id: "suru", name: "Suru", stateId: "kebbi" },
      { id: "wasagu-danko", name: "Wasagu/Danko", stateId: "kebbi" },
      { id: "yekun", name: "Yekun", stateId: "kebbi" },
      { id: "zuru", name: "Zuru", stateId: "kebbi" }
    ]
  },
  {
    id: "kogi",
    name: "Kogi",
    cities: [
      { id: "adoro", name: "Adoro", stateId: "kogi" },
      { id: "ajeokuta", name: "Ajeokuta", stateId: "kogi" },
      { id: "ankpa", name: "Ankpa", stateId: "kogi" },
      { id: "bassa", name: "Bassa", stateId: "kogi" },
      { id: "dekina", name: "Dekina", stateId: "kogi" },
      { id: "ibaji", name: "Ibaji", stateId: "kogi" },
      { id: "idanre", name: "Idanre", stateId: "kogi" },
      { id: "igalamela-odolu", name: "Igalamela-Odolu", stateId: "kogi" },
      { id: "ijumu", name: "Ijumu", stateId: "kogi" },
      { id: "kabba-bunu", name: "Kabba/Bunu", stateId: "kogi" },
      { id: "kogi", name: "Kogi", stateId: "kogi" },
      { id: "lokoja", name: "Lokoja", stateId: "kogi" },
      { id: "mopa-muro", name: "Mopa-Muro", stateId: "kogi" },
      { id: "ofl", name: "Ofl", stateId: "kogi" },
      { id: "ogori-magongo", name: "Ogori/Magongo", stateId: "kogi" },
      { id: "okehi", name: "Okehi", stateId: "kogi" },
      { id: "okene", name: "Okene", stateId: "kogi" },
      { id: "olaram", name: "Olaram", stateId: "kogi" },
      { id: "omala", name: "Omala", stateId: "kogi" },
      { id: "yagba-east", name: "Yagba East", stateId: "kogi" },
      { id: "yagba-west", name: "Yagba West", stateId: "kogi" }
    ]
  },
  {
    id: "kwara",
    name: "Kwara",
    cities: [
      { id: "asa", name: "Asa", stateId: "kwara" },
      { id: "baruten", name: "Baruten", stateId: "kwara" },
      { id: "edu", name: "Edu", stateId: "kwara" },
      { id: "ekiti", name: "Ekiti", stateId: "kwara" },
      { id: "ifelodun", name: "Ifelodun", stateId: "kwara" },
      { id: "ilorin-east", name: "Ilorin East", stateId: "kwara" },
      { id: "ilorin-south", name: "Ilorin South", stateId: "kwara" },
      { id: "ilorin-west", name: "Ilorin West", stateId: "kwara" },
      { id: "irepodun", name: "Irepodun", stateId: "kwara" },
      { id: "isin", name: "Isin", stateId: "kwara" },
      { id: "kaiama", name: "Kaiama", stateId: "kwara" },
      { id: "moro", name: "Moro", stateId: "kwara" },
      { id: "offa", name: "Offa", stateId: "kwara" },
      { id: "oke-ero", name: "Oke Ero", stateId: "kwara" },
      { id: "oyin", name: "Oyin", stateId: "kwara" },
      { id: "pategi", name: "Pategi", stateId: "kwara" }
    ]
  },
  {
    id: "lagos",
    name: "Lagos",
    cities: [
      { id: "agege", name: "Agege", stateId: "lagos" },
      { id: "ajeromi-ifelodun", name: "Ajeromi-Ifelodun", stateId: "lagos" },
      { id: "alimosho", name: "Alimosho", stateId: "lagos" },
      { id: "amusho", name: "Amuwo-Odofin", stateId: "lagos" },
      { id: "apapa", name: "Apapa", stateId: "lagos" },
      { id: "badagry", name: "Badagry", stateId: "lagos" },
      { id: "epe", name: "Epe", stateId: "lagos" },
      { id: "eti-osa", name: "Eti-Osa", stateId: "lagos" },
      { id: "ibeju-lekki", name: "Ibeju-Lekki", stateId: "lagos" },
      { id: "ifako-ijaiye", name: "Ifako-Ijaiye", stateId: "lagos" },
      { id: "ikeja", name: "Ikeja", stateId: "lagos" },
      { id: "ikorodu", name: "Ikorodu", stateId: "lagos" },
      { id: "kosofe", name: "Kosofe", stateId: "lagos" },
      { id: "lagos-island", name: "Lagos Island", stateId: "lagos" },
      { id: "lagos-mainland", name: "Lagos Mainland", stateId: "lagos" },
      { id: "mushin", name: "Mushin", stateId: "lagos" },
      { id: "oshima", name: "Oshima", stateId: "lagos" },
      { id: "oshodi-isolo", name: "Oshodi-Isolo", stateId: "lagos" },
      { id: "shomolu", name: "Shomolu", stateId: "lagos" },
      { id: "surulere", name: "Surulere", stateId: "lagos" }
    ]
  },
  {
    id: "nasarawa",
    name: "Nasarawa",
    cities: [
      { id: "akeke", name: "Akeke", stateId: "nasarawa" },
      { id: "amani", name: "Amani", stateId: "nasarawa" },
      { id: "d", name: "D", stateId: "nasarawa" },
      { id: "gado", name: "Gado", stateId: "nasarawa" },
      { id: "keana", name: "Keana", stateId: "nasarawa" },
      { id: "kefi", name: "Kefi", stateId: "nasarawa" },
      { id: "kokona", name: "Kokona", stateId: "nasarawa" },
      { id: "lafia", name: "Lafia", stateId: "nasarawa" },
      { id: "nasarawa", name: "Nasarawa", stateId: "nasarawa" },
      { id: "nasarawa-eggon", name: "Nasarawa Eggon", stateId: "nasarawa" },
      { id: "obi", name: "Obi", stateId: "nasarawa" },
      { id: "omani", name: "Omani", stateId: "nasarawa" },
      { id: "totai", name: "Totai", stateId: "nasarawa" },
      { id: "wamba", name: "Wamba", stateId: "nasarawa" }
    ]
  },
  {
    id: "niger",
    name: "Niger",
    cities: [
      { id: "agaie", name: "Agaie", stateId: "niger" },
      { id: "agwara", name: "Agwara", stateId: "niger" },
      { id: "bida", name: "Bida", stateId: "niger" },
      { id: "borgu", name: "Borgu", stateId: "niger" },
      { id: "bosso", name: "Bosso", stateId: "niger" },
      { id: "chanchaga", name: "Chanchaga", stateId: "niger" },
      { id: "edati", name: "Edati", stateId: "niger" },
      { id: "gbako", name: "Gbako", stateId: "niger" },
      { id: "gurara", name: "Gurara", stateId: "niger" },
      { id: "katcha", name: "Katcha", stateId: "niger" },
      { id: "kontagora", name: "Kontagora", stateId: "niger" },
      { id: "lapai", name: "Lapai", stateId: "niger" },
      { id: "lavun", name: "Lavun", stateId: "niger" },
      { id: "magama", name: "Magama", stateId: "niger" },
      { id: "mariga", name: "Mariga", stateId: "niger" },
      { id: "mashegu", name: "Mashegu", stateId: "niger" },
      { id: "mokwa", name: "Mokwa", stateId: "niger" },
      { id: "muya", name: "Muya", stateId: "niger" },
      { id: "paikoro", name: "Paikoro", stateId: "niger" },
      { id: "rafsanjani", name: "Rafsanjani", stateId: "niger" },
      { id: "rijau", name: "Rijau", stateId: "niger" },
      { id: "shiroro", name: "Shiroro", stateId: "niger" },
      { id: "suleja", name: "Suleja", stateId: "niger" },
      { id: "tagina", name: "Tagina", stateId: "niger" },
      { id: "wan", name: "Wan", stateId: "niger" },
      { id: "wushishi", name: "Wushishi", stateId: "niger" }
    ]
  },
  {
    id: "ogun",
    name: "Ogun",
    cities: [
      { id: "abeokuta-north", name: "Abeokuta North", stateId: "ogun" },
      { id: "abeokuta-south", name: "Abeokuta South", stateId: "ogun" },
      { id: "ado-odo-ota", name: "Ado-Odo/Ota", stateId: "ogun" },
      { id: "ewekoro", name: "Ewekoro", stateId: "ogun" },
      { id: "ifu", name: "Ifu", stateId: "ogun" },
      { id: "ijebu-ode", name: "Ijebu-Ode", stateId: "ogun" },
      { id: "ikene", name: "Ikene", stateId: "ogun" },
      { id: "ile-ife-north", name: "Ile Ife North", stateId: "ogun" },
      { id: "imo", name: "Imo", stateId: "ogun" },
      { id: "ipokia", name: "Ipokia", stateId: "ogun" },
      { id: "obafemi-owode", name: "Obafemi-Owode", stateId: "ogun" },
      { id: "ogun-waterside", name: "Ogun Waterside", stateId: "ogun" },
      { id: "oduogbolu", name: "Oduogbolu", stateId: "ogun" },
      { id: "ofo", name: "Ofo", stateId: "ogun" },
      { id: "remo-north", name: "Remo North", stateId: "ogun" },
      { id: "sagamu", name: "Sagamu", stateId: "ogun" },
      { id: "yenwa", name: "Yenwa", stateId: "ogun" }
    ]
  },
  {
    id: "ondo",
    name: "Ondo",
    cities: [
      { id: "akoko-north-east", name: "Akoko North-East", stateId: "ondo" },
      { id: "akoko-north-west", name: "Akoko North-West", stateId: "ondo" },
      { id: "akoko-south-east", name: "Akoko South-East", stateId: "ondo" },
      { id: "akoko-south-west", name: "Akoko South-West", stateId: "ondo" },
      { id: "akure-north", name: "Akure North", stateId: "ondo" },
      { id: "akure-south", name: "Akure South", stateId: "ondo" },
      { id: "ese-odo", name: "Ese Odo", stateId: "ondo" },
      { id: "id", name: "ID", stateId: "ondo" },
      { id: "idanre", name: "Idanre", stateId: "ondo" },
      { id: "if", name: "IF", stateId: "ondo" },
      { id: "igbogini", name: "Igbogini", stateId: "ondo" },
      { id: "ile-oluji-okeigbo", name: "Ile Oluji/Okeigbo", stateId: "ondo" },
      { id: "irele", name: "Irele", stateId: "ondo" },
      { id: "okiti-pupa", name: "Okiti Pupa", stateId: "ondo" },
      { id: "ondo-east", name: "Ondo East", stateId: "ondo" },
      { id: "ondo-west", name: "Ondo West", stateId: "ondo" },
      { id: "ose", name: "Ose", stateId: "ondo" },
      { id: "owo", name: "Owo", stateId: "ondo" }
    ]
  },
  {
    id: "osun",
    name: "Osun",
    cities: [
      { id: "a", name: "A", stateId: "osun" },
      { id: "aiya-owode", name: "Aiya Owode", stateId: "osun" },
      { id: "atol", name: "Atol", stateId: "osun" },
      { id: "ayedaade", name: "Ayedaade", stateId: "osun" },
      { id: "ayedere", name: "Ayedere", stateId: "osun" },
      { id: "boluwaduro", name: "Boluwaduro", stateId: "osun" },
      { id: "boripe", name: "Boripe", stateId: "osun" },
      { id: "ede-north", name: "Ede North", stateId: "osun" },
      { id: "ede-south", name: "Ede South", stateId: "osun" },
      { id: "egbedore", name: "Egbedore", stateId: "osun" },
      { id: "ejigbo", name: "Ejigbo", stateId: "osun" },
      { id: "ifelodun", name: "Ifelodun", stateId: "osun" },
      { id: "ifesuy", name: "Ifesuy", stateId: "osun" },
      { id: "igbi", name: "Igbi", stateId: "osun" },
      { id: "ile-ife-east", name: "Ile Ife East", stateId: "osun" },
      { id: "ile-ife-north", name: "Ile Ife North", stateId: "osun" },
      { id: "ile-ife-south", name: "Ile Ife South", stateId: "osun" },
      { id: "ile-ife-central", name: "Ile Ife Central", stateId: "osun" },
      { id: "ilet", name: "Ilet", stateId: "osun" },
      { id: "il", name: "Il", stateId: "osun" },
      { id: "irepodun", name: "Irepodun", stateId: "osun" },
      { id: "irewole", name: "Irewole", stateId: "osun" },
      { id: "isin", name: "Isin", stateId: "osun" },
      { id: "iwo", name: "Iwo", stateId: "osun" },
      { id: "obokun", name: "Obokun", stateId: "osun" },
      { id: "odo-otin", name: "Odo-Otin", stateId: "osun" },
      { id: "ola-oluwa", name: "Ola-Oluwa", stateId: "osun" },
      { id: "omod", name: "Omod", stateId: "osun" },
      { id: "osogbo", name: "Osogbo", stateId: "osun" },
      { id: "oyen", name: "Oyen", stateId: "osun" }
    ]
  },
  {
    id: "oyo",
    name: "Oyo",
    cities: [
      { id: "akinyele", name: "Akinyele", stateId: "oyo" },
      { id: "atiba", name: "Atiba", stateId: "oyo" },
      { id: "atiwa", name: "Atiwa", stateId: "oyo" },
      { id: "egbeda", name: "Egbeda", stateId: "oyo" },
      { id: "ibarapa-central", name: "Ibarapa Central", stateId: "oyo" },
      { id: "ibarapa-east", name: "Ibarapa East", stateId: "oyo" },
      { id: "ibarapa-north", name: "Ibarapa North", stateId: "oyo" },
      { id: "id", name: "Id", stateId: "oyo" },
      { id: "ido", name: "Ido", stateId: "oyo" },
      { id: "ifelodun", name: "Ifelodun", stateId: "oyo" },
      { id: "igbo-ora", name: "Igbo Ora", stateId: "oyo" },
      { id: "igbo-olohu", name: "Igbo Olohu", stateId: "oyo" },
      { id: "iken", name: "Iken", stateId: "oyo" },
      { id: "kajola", name: "Kajola", stateId: "oyo" },
      { id: "lagelu", name: "Lagelu", stateId: "oyo" },
      { id: "ogbomosho-north", name: "Ogbomosho North", stateId: "oyo" },
      { id: "ogbomosho-south", name: "Ogbomosho South", stateId: "oyo" },
      { id: "ogo-oluwa", name: "Ogo Oluwa", stateId: "oyo" },
      { id: "olol", name: "Olol", stateId: "oyo" },
      { id: "ona-ara", name: "Ona Ara", stateId: "oyo" },
      { id: "orelope", name: "Orelope", stateId: "oyo" },
      { id: "ori-ire", name: "Ori Ire", stateId: "oyo" },
      { id: "oyo-east", name: "Oyo East", stateId: "oyo" },
      { id: "oyo-west", name: "Oyo West", stateId: "oyo" },
      { id: "saki-east", name: "Saki East", stateId: "oyo" },
      { id: "saki-west", name: "Saki West", stateId: "oyo" },
      { id: "surulere", name: "Surulere", stateId: "oyo" }
    ]
  },
  {
    id: "plateau",
    name: "Plateau",
    cities: [
      { id: "barkin-ladi", name: "Barkin Ladi", stateId: "plateau" },
      { id: "bassa", name: "Bassa", stateId: "plateau" },
      { id: "bokkos", name: "Bokkos", stateId: "plateau" },
      { id: "jos-east", name: "Jos East", stateId: "plateau" },
      { id: "jos-north", name: "Jos North", stateId: "plateau" },
      { id: "jos-south", name: "Jos South", stateId: "plateau" },
      { id: "karen", name: "Karen", stateId: "plateau" },
      { id: "langtang-north", name: "Langtang North", stateId: "plateau" },
      { id: "langtang-south", name: "Langtang South", stateId: "plateau" },
      { id: "mangu", name: "Mangu", stateId: "plateau" },
      { id: "mikang", name: "Mikang", stateId: "plateau" },
      { id: "obi", name: "Obi", stateId: "plateau" },
      { id: "panzakin", name: "Panzakin", stateId: "plateau" },
      { id: "qua-an-pan", name: "Qua'an Pan", stateId: "plateau" },
      { id: "riyom", name: "Riyom", stateId: "plateau" },
      { id: "shendam", name: "Shendam", stateId: "plateau" },
      { id: "wase", name: "Wase", stateId: "plateau" }
    ]
  },
  {
    id: "rivers",
    name: "Rivers",
    cities: [
      { id: "abic", name: "Abic", stateId: "rivers" },
      { id: "ahoada-east", name: "Ahoada East", stateId: "rivers" },
      { id: "ahoada-west", name: "Ahoada West", stateId: "rivers" },
      { id: "akah", name: "Akah", stateId: "rivers" },
      { id: "andoni", name: "Andoni", stateId: "rivers" },
      { id: "degema", name: "Degema", stateId: "rivers" },
      { id: "emouha", name: "Emouha", stateId: "rivers" },
      { id: "eleme", name: "Eleme", stateId: "rivers" },
      { id: "etche", name: "Etche", stateId: "rivers" },
      { id: "gokana", name: "Gokana", stateId: "rivers" },
      { id: "ikwerre", name: "Ikwerre", stateId: "rivers" },
      { id: "khana", name: "Khana", stateId: "rivers" },
      { id: "obio-akpor", name: "Obio/Akpor", stateId: "rivers" },
      { id: "ogba-egbema-ndoni", name: "Ogba/Egbema/Ndoni", stateId: "rivers" },
      { id: "ogbaji", name: "Ogbaji", stateId: "rivers" },
      { id: "omuma", name: "Omuma", stateId: "rivers" },
      { id: "opobo-nkoro", name: "Opobo/Nkoro", stateId: "rivers" },
      { id: "pari", name: "Pari", stateId: "rivers" },
      { id: "ph", name: "Ph", stateId: "rivers" },
      { id: "tai", name: "Tai", stateId: "rivers" }
    ]
  },
  {
    id: "sokoto",
    name: "Sokoto",
    cities: [
      { id: "binji", name: "Binji", stateId: "sokoto" },
      { id: "bodinga", name: "Bodinga", stateId: "sokoto" },
      { id: "dange-shuni", name: "Dange-Shuni", stateId: "sokoto" },
      { id: "g", name: "G", stateId: "sokoto" },
      { id: "goronyo", name: "Goronyo", stateId: "sokoto" },
      { id: "gudu", name: "Gudu", stateId: "sokoto" },
      { id: "gwadabawa", name: "Gwadabawa", stateId: "sokoto" },
      { id: "illela", name: "Illela", stateId: "sokoto" },
      { id: "kebbe", name: "Kebbe", stateId: "sokoto" },
      { id: "kware", name: "Kware", stateId: "sokoto" },
      { id: "rabah", name: "Rabah", stateId: "sokoto" },
      { id: "sab", name: "Sab", stateId: "sokoto" },
      { id: "shagari", name: "Shagari", stateId: "sokoto" },
      { id: "silame", name: "Silame", stateId: "sokoto" },
      { id: "sokoto-north", name: "Sokoto North", stateId: "sokoto" },
      { id: "sokoto-south", name: "Sokoto South", stateId: "sokoto" },
      { id: "tambwal", name: "Tambwal", stateId: "sokoto" },
      { id: "tangaza", name: "Tangaza", stateId: "sokoto" },
      { id: "t", name: "T", stateId: "sokoto" },
      { id: "wamako", name: "Wamako", stateId: "sokoto" },
      { id: "wurno", name: "Wurno", stateId: "sokoto" },
      { id: "yabo", name: "Yabo", stateId: "sokoto" }
    ]
  },
  {
    id: "taraba",
    name: "Taraba",
    cities: [
      { id: "ardokola", name: "Ardokola", stateId: "taraba" },
      { id: "bali", name: "Bali", stateId: "taraba" },
      { id: "donga", name: "Donga", stateId: "taraba" },
      { id: "gashaka", name: "Gashaka", stateId: "taraba" },
      { id: "gassol", name: "Gassol", stateId: "taraba" },
      { id: "ibi", name: "Ibi", stateId: "taraba" },
      { id: "jalingo", name: "Jalingo", stateId: "taraba" },
      { id: "karim-lamido", name: "Karim Lamido", stateId: "taraba" },
      { id: "k", name: "K", stateId: "taraba" },
      { id: "lau", name: "Lau", stateId: "taraba" },
      { id: "nguroje", name: "Nguroje", stateId: "taraba" },
      { id: "sardauna", name: "Sardauna", stateId: "taraba" },
      { id: "takum", name: "Takum", stateId: "taraba" },
      { id: "usi", name: "Usi", stateId: "taraba" },
      { id: "wukari", name: "Wukari", stateId: "taraba" },
      { id: "y", name: "Y", stateId: "taraba" },
      { id: "zing", name: "Zing", stateId: "taraba" }
    ]
  },
  {
    id: "yobe",
    name: "Yobe",
    cities: [
      { id: "bade", name: "Bade", stateId: "yobe" },
      { id: "bursari", name: "Bursari", stateId: "yobe" },
      { id: "damaturu", name: "Damaturu", stateId: "yobe" },
      { id: "fika", name: "Fika", stateId: "yobe" },
      { id: "fune", name: "Fune", stateId: "yobe" },
      { id: "geidam", name: "Geidam", stateId: "yobe" },
      { id: "g", name: "G", stateId: "yobe" },
      { id: "gujba", name: "Gujba", stateId: "yobe" },
      { id: "gulani", name: "Gulani", stateId: "yobe" },
      { id: "jakusko", name: "Jakusko", stateId: "yobe" },
      { id: "karasuwa", name: "Karasuwa", stateId: "yobe" },
      { id: "machina", name: "Machina", stateId: "yobe" },
      { id: "nangere", name: "Nangere", stateId: "yobe" },
      { id: "potiskum", name: "Potiskum", stateId: "yobe" },
      { id: "t", name: "T", stateId: "yobe" },
      { id: "yunusari", name: "Yunusari", stateId: "yobe" },
      { id: "z", name: "Z", stateId: "yobe" }
    ]
  },
  {
    id: "zamfara",
    name: "Zamfara",
    cities: [
      { id: "anka", name: "Anka", stateId: "zamfara" },
      { id: "bakura", name: "Bakura", stateId: "zamfara" },
      { id: "birnin-magaji", name: "Birnin Magaji", stateId: "zamfara" },
      { id: "bukkuyum", name: "Bukkuyum", stateId: "zamfara" },
      { id: "bungudu", name: "Bungudu", stateId: "zamfara" },
      { id: "gummi", name: "Gummi", stateId: "zamfara" },
      { id: "gusau", name: "Gusau", stateId: "zamfara" },
      { id: "kaura-namoda", name: "Kaura Namoda", stateId: "zamfara" },
      { id: "maradun", name: "Maradun", stateId: "zamfara" },
      { id: "shinkafi", name: "Shinkafi", stateId: "zamfara" },
      { id: "talata-mafara", name: "Talata Mafara", stateId: "zamfara" },
      { id: "t", name: "T", stateId: "zamfara" },
      { id: "zurmi", name: "Zurmi", stateId: "zamfara" }
    ]
  },
  {
    id: "fct",
    name: "Federal Capital Territory",
    cities: [
      { id: "abaji", name: "Abaji", stateId: "fct" },
      { id: "abuja-municipal", name: "Abuja Municipal", stateId: "fct" },
      { id: "gwagwalada", name: "Gwagwalada", stateId: "fct" },
      { id: "k", name: "K", stateId: "fct" },
      { id: "kuje", name: "Kuje", stateId: "fct" },
      { id: "s", name: "S", stateId: "fct" }
    ]
  }
];